services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock # Montera Docker socket
    ports:
      - "9090:9090"
    networks:
      - fwk-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3005"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - fwk-net

networks:
  fwk-net:
    driver: bridge
