global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "fwk-auth"
    static_configs:
      - targets: ["localhost:3002"] # Eller den port där din Docker-miljö är exponerad för Prometheus
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock" # Detta används för att skrapa Docker-metrik
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: "container"
